DROP TABLE IF EXISTS movie_actor;
DROP TABLE IF EXISTS watch_movie;
DROP TABLE IF EXISTS favorite_actor;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS actor;
DROP TABLE IF EXISTS movie;


CREATE TABLE account
(
    account_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    email      VARCHAR(250) DEFAULT NULL
);

insert into account(first_name, last_name, email)
values ('Ihor', 'Bukin', 'ihor.bukin@email.com');

create table actor
(
    actor_id   INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name  VARCHAR(50)
);

CREATE TABLE MOVIE
(
    movie_id    INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL
);

CREATE TABLE MOVIE_ACTOR
(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    movie_id INT NOT NULL,
    actor_id INT NOT NULL
);

ALTER TABLE movie_actor
    ADD FOREIGN KEY (movie_id)
        REFERENCES movie (movie_id);

ALTER TABLE movie_actor
    ADD FOREIGN KEY (actor_id)
        REFERENCES actor (actor_id);

CREATE TABLE WATCH_MOVIE
(
    movie_id INT NOT NULL,
    user_id  INT NOT NULL
);

CREATE TABLE favorite_actor
(
    actor_id INT NOT NULL,
    user_id  INT NOT NULL
);

ALTER TABLE watch_movie
    ADD FOREIGN KEY (movie_id)
        REFERENCES movie (movie_id);

ALTER TABLE watch_movie
    ADD FOREIGN KEY (user_id)
        REFERENCES account (account_id);

INSERT INTO movie(name, description)
VALUES ('Three Monks', 'Some description'),
       ('Force of One, A', 'Some description'),
       ('Dharti Ke Lal', 'Some description'),
       ('Two Drops of Water', 'Some description'),
       ('Damn Yankees', 'Some description'),
       ('Pajama Game, The', 'Some description'),
       ('Corporation, The', 'Some description'),
       ('Okhota na lis', 'Some description'),
       ('Train Has Stopped, The', 'Some description'),
       ('Parad planet', 'Some description'),
       ('Time of a Dancer', 'Some description'),
       ('Iceberg, L', 'Some description'),
       ('Good Girls, The', 'Some description'),
       ('Quam Tristis, O', 'Some description'),
       ('Bidaya wa nihaya', 'Some description'),
       ('Water Carrier Has Died, The', 'Some description'),
       ('State of the World', 'Some description'),
       ('Agraharathil Kazhuthai', 'Some description'),
       ('Amma Ariyan', 'Some description'),
       ('Airplane!', 'Some description'),
       ('Top Secret!', 'Some description'),
       ('Ruthless People', 'Some description'),
       ('Adam & Paul', 'Some description'),
       ('Garage', 'Some description'),
       ('Frank', 'Some description'),
       ('Room', 'Some description'),
       ('Mission: Impossible III', 'Some description'),
       ('Star Trek', 'Some description'),
       ('Super 8', 'Some description'),
       ('Star Wars: The Force Awakens', 'Some description'),
       ('Boy and the World', 'Some description'),
       ('Ranas Wedding', 'Some description'),
       ('Ford Transit', 'Some description'),
       ('Paradise Now', 'Some description'),
       ('Omar', 'Some description'),
       ('Vedreba', 'Some description'),
       ('Wishing Tree, The', 'Some description'),
       ('Repentance', 'Some description'),
       ('Tashan', 'Some description'),
       ('Manufacturing Consent: Noam Chomsky and the Media', 'Some description'),
       ('Beer Chase', 'Some description'),
       ('Last Hole, The', 'Some description'),
       ('Raft of the Medusa, The/Splav Meduze', 'Some description'),
       ('Red Boogie', 'Some description'),
       ('A.K.A. Serial Killer', 'Some description'),
       ('Red Army, The/PFLP: Declaration of World War', 'Some description'),
       ('Prisoner/Terrorist', 'Some description'),
       ('Artist of Fasting', 'Some description'),
       ('Word is Out', 'Some description'),
       ('Satans Sadists', 'Some description'),
       ('Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The', 'Some description'),
       ('Shrek', 'Some description'),
       ('Shrek 2', 'Some description'),
       ('Forest for the Trees, The', 'Some description'),
       ('Everyone Else', 'Some description'),
       ('Toni Erdmann', 'Some description'),
       ('Lodz Ghetto', 'Some description'),
       ('Under the Skin [1997]', 'Some description'),
       ('Bordello of Blood', 'Some description'),
       ('Up in Smoke', 'Some description'),
       ('Ladies and Gentlemen, The Fabulous Stains', 'Some description'),
       ('Bagdad Café', 'Some description'),
       ('Koma', 'Some description'),
       ('Man is Armed, The', 'Some description'),
       ('Filmblok (0/1/2)', 'Some description'),
       ('Porviroscope', 'Some description'),
       ('Kol Ho Naa Ho', 'Some description'),
       ('Gone Baby Gone', 'Some description'),
       ('Town, The', 'Some description'),
       ('Argo', 'Some description'),
       ('Im Still Here', 'Some description'),
       ('Hemlock', 'Some description'),
       ('In the Street', 'Some description'),
       ('My Neighbor, My Killer', 'Some description'),
       ('No-One or Everyone', 'Some description'),
       ('Valentin', 'Some description'),
       ('Lake House, The', 'Some description'),
       ('One Hundred Children Waiting for a Train', 'Some description'),
       ('Aquí se construye (o Ya no existe el lugar donde nací)', 'Some description'),
       ('Otro día, El', 'Some description'),
       ('Quarto mandamiento, El', 'Some description'),
       ('Unsung Heroine', 'Some description'),
       ('Hunchback of the Morgue', 'Some description'),
       ('Wild Style', 'Some description'),
       ('Darkland', 'Some description'),
       ('Mukhsin', 'Some description'),
       ('Srabon Megher Din', 'Some description'),
       ('Fishermans Fire', 'Some description'),
       ('Tito on Ice', 'Some description'),
       ('Långt borta och nära', 'Some description'),
       ('Consolation Service', 'Some description'),
       ('Color of Love, The', 'Some description'),
       ('She Puppet', 'Some description'),
       ('Deadman, The', 'Some description'),
       ('Disturbing the Peace', 'Some description'),
       ('Madame Satã', 'Some description'),
       ('Love for Sale', 'Some description'),
       ('I Travel Because I Have To, I Come Back Because I Love You', 'Some description'),
       ('Until the Light Takes Us', 'Some description'),
       ('High Tension', 'Some description');


INSERT INTO actor (first_name, last_name)
VALUES ('AADEN', 'AADEN'),
       ('AADIT', 'AADIT'),
       ('AADVIK', 'AADVIK'),
       ('AAIDEN', 'AAIDEN'),
       ('AARAV', 'AARAV'),
       ('AARIZ', 'AARIZ'),
       ('AARUSH', 'AARUSH'),
       ('AARYAN', 'AARYAN'),
       ('AKASH', 'AKASH'),
       ('AKHIL', 'AKHIL'),
       ('AKIRA', 'AKIRA'),
       ('AKIVA', 'AKIVA'),
       ('AKSEL', 'AKSEL'),
       ('ALAN', 'ALAN'),
       ('ALARIC', 'ALARIC'),
       ('ALBERT', 'ALBERT'),
       ('ALBERTO', 'ALBERTO'),
       ('ALDAIR', 'ALDAIR'),
       ('ALDEN', 'ALDEN'),
       ('ALDO', 'ALDO'),
       ('ALEC', 'ALEC'),
       ('ALEJANDRO', 'ALEJANDRO'),
       ('ALEK', 'ALEK'),
       ('ALEKSANDER', 'ALEKSANDER'),
       ('ALESSANDRO', 'ALESSANDRO'),
       ('ALESSIO', 'ALESSIO'),
       ('ALEX', 'ALEX'),
       ('ALEXANDER', 'ALEXANDER'),
       ('ALEXANDRO', 'ALEXANDRO'),
       ('ALEXEY', 'ALEXEY'),
       ('ALEXIS', 'ALEXIS'),
       ('ALEXZANDER', 'ALEXZANDER'),
       ('ALFONSO', 'ALFONSO'),
       ('ALFRED', 'ALFRED'),
       ('ALFREDO', 'ALFREDO'),
       ('ALI', 'ALI'),
       ('ALIJAH', 'ALIJAH'),
       ('ALISTAIR', 'ALISTAIR'),
       ('ALLAN', 'ALLAN'),
       ('ALLEN', 'ALLEN'),
       ('ALONSO', 'ALONSO'),
       ('ALONZO', 'ALONZO'),
       ('ALP', 'ALP'),
       ('ALSTON', 'ALSTON'),
       ('ALTON', 'ALTON'),
       ('ALVARO', 'ALVARO'),
       ('ALVIN', 'ALVIN'),
       ('AMADEUS', 'AMADEUS'),
       ('AMADO', 'AMADO'),
       ('AMAR', 'AMAR'),
       ('AMARE', 'AMARE'),
       ('AMARI', 'AMARI'),
       ('AMAZIAH', 'AMAZIAH'),
       ('AMBROSE', 'AMBROSE'),
       ('AMEER', 'AMEER'),
       ('AMIN', 'AMIN'),
       ('AMIR', 'AMIR'),
       ('AMOS', 'AMOS'),
       ('AN', 'AN'),
       ('ANAKIN', 'ANAKIN'),
       ('ANAY', 'ANAY'),
       ('ANDER', 'ANDER'),
       ('ANDERS', 'ANDERS'),
       ('ANDERSON', 'ANDERSON'),
       ('ANDRE', 'ANDRE'),
       ('ANDREAS', 'ANDREAS'),
       ('ANDREI', 'ANDREI'),
       ('ANDRES', 'ANDRES'),
       ('ANDREW', 'ANDREW'),
       ('ANDREY', 'ANDREY'),
       ('ANDY', 'ANDY'),
       ('ANGAD', 'ANGAD'),
       ('ANGEL', 'ANGEL'),
       ('ANGELO', 'ANGELO'),
       ('ANSEL', 'ANSEL'),
       ('ANSH', 'ANSH'),
       ('ANSON', 'ANSON'),
       ('ANTHONY', 'ANTHONY'),
       ('ANTOINE', 'ANTOINE'),
       ('ANTON', 'ANTON'),
       ('ANTONIO', 'ANTONIO'),
       ('ANTONY', 'ANTONY'),
       ('APOLLO', 'APOLLO'),
       ('ARAM', 'ARAM'),
       ('ARCHER', 'ARCHER'),
       ('ARCHIE', 'ARCHIE'),
       ('ARDEN', 'ARDEN'),
       ('AREG', 'AREG'),
       ('AREN', 'AREN'),
       ('ARES', 'ARES'),
       ('ARHAM', 'ARHAM'),
       ('ARI', 'ARI'),
       ('ARIA', 'ARIA'),
       ('ARIAN', 'ARIAN'),
       ('ARIEL', 'ARIEL'),
       ('ARIES', 'ARIES'),
       ('ARIN', 'ARIN'),
       ('ARIS', 'ARIS'),
       ('ARIUS', 'ARIUS'),
       ('ARJAN', 'ARJAN'),
       ('ARJUN', 'ARJUN'),
       ('ARLEY', 'ARLEY'),
       ('ARLO', 'ARLO'),
       ('ARMAAN', 'ARMAAN'),
       ('ARMAN', 'ARMAN'),
       ('ARMANDO', 'ARMANDO'),
       ('ARMANI', 'ARMANI'),
       ('ARMEN', 'ARMEN'),
       ('ARMIN', 'ARMIN'),
       ('ARNAV', 'ARNAV'),
       ('ARNOLD', 'ARNOLD'),
       ('ARNULFO', 'ARNULFO'),
       ('ARON', 'ARON'),
       ('ARROW', 'ARROW'),
       ('ARSALAN', 'ARSALAN'),
       ('ARSEN', 'ARSEN'),
       ('ARTEM', 'ARTEM'),
       ('ARTHUR', 'ARTHUR'),
       ('ARTURO', 'ARTURO'),
       ('ARVIN', 'ARVIN'),
       ('ARYA', 'ARYA'),
       ('ARYAN', 'ARYAN'),
       ('ASA', 'ASA'),
       ('ASH', 'ASH'),
       ('ASHER', 'ASHER'),
       ('ASHTON', 'ASHTON'),
       ('ASLAN', 'ASLAN'),
       ('ASTON', 'ASTON'),
       ('ATHAN', 'ATHAN'),
       ('ATHARV', 'ATHARV'),
       ('ATLAS', 'ATLAS'),
       ('ATOM', 'ATOM'),
       ('ATREYU', 'ATREYU'),
       ('ATTICUS', 'ATTICUS'),
       ('AUBREY', 'AUBREY'),
       ('AUGUST', 'AUGUST'),
       ('AUGUSTIN', 'AUGUSTIN'),
       ('AUGUSTINE', 'AUGUSTINE'),
       ('AUGUSTUS', 'AUGUSTUS'),
       ('AURELIO', 'AURELIO'),
       ('AUSTEN', 'AUSTEN'),
       ('AUSTIN', 'AUSTIN'),
       ('AVAN', 'AVAN'),
       ('AVEN', 'AVEN'),
       ('AVERY', 'AVERY'),
       ('AVI', 'AVI'),
       ('AVYAAN', 'AVYAAN'),
       ('AVYAN', 'AVYAN'),
       ('AXEL', 'AXEL'),
       ('AXL', 'AXL'),
       ('AXTON', 'AXTON'),
       ('AYAAN', 'AYAAN'),
       ('AYAANSH', 'AYAANSH'),
       ('AYAN', 'AYAN'),
       ('AYANSH', 'AYANSH'),
       ('AYDAN', 'AYDAN'),
       ('AYDEN', 'AYDEN'),
       ('AYDIN', 'AYDIN'),
       ('AYLAN', 'AYLAN'),
       ('AYUSH', 'AYUSH'),
       ('AZAEL', 'AZAEL'),
       ('AZAIAH', 'AZAIAH'),
       ('AZARIAH', 'AZARIAH'),
       ('AZIEL', 'AZIEL'),
       ('AZLAN', 'AZLAN'),
       ('AZRAEL', 'AZRAEL'),
       ('AZRIEL', 'AZRIEL'),
       ('BABY', 'BABY'),
       ('BAILEY', 'BAILEY'),
       ('BAKER', 'BAKER'),
       ('BALTAZAR', 'BALTAZAR'),
       ('BARON', 'BARON'),
       ('BARRETT', 'BARRETT'),
       ('BARRON', 'BARRON'),
       ('BARRY', 'BARRY'),
       ('BASTIAN', 'BASTIAN'),
       ('BAYLOR', 'BAYLOR'),
       ('BEAR', 'BEAR'),
       ('BEAU', 'BEAU'),
       ('BECK', 'BECK'),
       ('BECKETT', 'BECKETT'),
       ('BECKHAM', 'BECKHAM'),
       ('BEN', 'BEN'),
       ('BENAIAH', 'BENAIAH'),
       ('BENEDICT', 'BENEDICT'),
       ('BENICIO', 'BENICIO'),
       ('BENITO', 'BENITO'),
       ('BENJAMIN', 'BENJAMIN'),
       ('BENNETT', 'BENNETT'),
       ('BENNY', 'BENNY'),
       ('BENSON', 'BENSON'),
       ('BENTLEY', 'BENTLEY'),
       ('BENTON', 'BENTON'),
       ('BERNARD', 'BERNARD'),
       ('BERNARDO', 'BERNARDO'),
       ('BILAL', 'BILAL'),
       ('BILL', 'BILL'),
       ('BILLY', 'BILLY'),
       ('BISHOP', 'BISHOP'),
       ('BJORN', 'BJORN'),
       ('BLAINE', 'BLAINE'),
       ('BLAISE', 'BLAISE'),
       ('BLAKE', 'BLAKE'),
       ('BLAZE', 'BLAZE'),
       ('BO', 'BO'),
       ('BOAZ', 'BOAZ'),
       ('BOBBY', 'BOBBY'),
       ('BODE', 'BODE'),
       ('BODEN', 'BODEN'),
       ('BODHI', 'BODHI'),
       ('BODI', 'BODI'),
       ('BODIE', 'BODIE'),
       ('BOONE', 'BOONE'),
       ('BORIS', 'BORIS'),
       ('BORNA', 'BORNA'),
       ('BOSTON', 'BOSTON'),
       ('BOWEN', 'BOWEN'),
       ('BOWIE', 'BOWIE'),
       ('BOYD', 'BOYD'),
       ('BRADEN', 'BRADEN'),
       ('BRADLEY', 'BRADLEY'),
       ('BRADY', 'BRADY'),
       ('BRADYN', 'BRADYN'),
       ('BRAEDEN', 'BRAEDEN'),
       ('BRAIDEN', 'BRAIDEN'),
       ('BRANDEN', 'BRANDEN'),
       ('BRANDON', 'BRANDON'),
       ('BRANSON', 'BRANSON'),
       ('BRANTLEY', 'BRANTLEY'),
       ('BRAULIO', 'BRAULIO'),
       ('BRAXTON', 'BRAXTON'),
       ('BRAYAN', 'BRAYAN'),
       ('BRAYDEN', 'BRAYDEN'),
       ('BRAYDON', 'BRAYDON'),
       ('BRAYLEN', 'BRAYLEN'),
       ('BRAYLON', 'BRAYLON'),
       ('BRECKEN', 'BRECKEN'),
       ('BRENDAN', 'BRENDAN'),
       ('BRENDEN', 'BRENDEN'),
       ('BRENDON', 'BRENDON'),
       ('BRENNAN', 'BRENNAN'),
       ('BRENT', 'BRENT'),
       ('BRENTLEY', 'BRENTLEY'),
       ('BRENTON', 'BRENTON'),
       ('BRETT', 'BRETT'),
       ('BRIAN', 'BRIAN'),
       ('BRIGGS', 'BRIGGS'),
       ('BRIXTON', 'BRIXTON'),
       ('BROCK', 'BROCK'),
       ('BRODERICK', 'BRODERICK'),
       ('BRODIE', 'BRODIE'),
       ('BRODY', 'BRODY'),
       ('BRONSON', 'BRONSON'),
       ('BROOKLYN', 'BROOKLYN'),
       ('BROOKS', 'BROOKS'),
       ('BRUCE', 'BRUCE'),
       ('BRUNO', 'BRUNO'),
       ('BRYAN', 'BRYAN'),
       ('BRYANT', 'BRYANT'),
       ('BRYCE', 'BRYCE'),
       ('BRYCEN', 'BRYCEN'),
       ('BRYDEN', 'BRYDEN'),
       ('BRYSEN', 'BRYSEN'),
       ('BRYSON', 'BRYSON'),
       ('BYRON', 'BYRON'),
       ('CADE', 'CADE'),
       ('CADEN', 'CADEN'),
       ('CAELAN', 'CAELAN'),
       ('CAESAR', 'CAESAR'),
       ('CAIDEN', 'CAIDEN'),
       ('CAIN', 'CAIN'),
       ('CAIRO', 'CAIRO'),
       ('CAL', 'CAL'),
       ('CALEB', 'CALEB'),
       ('CALLAHAN', 'CALLAHAN'),
       ('CALLAN', 'CALLAN'),
       ('CALLEN', 'CALLEN'),
       ('CALLUM', 'CALLUM'),
       ('CALVIN', 'CALVIN'),
       ('CAM', 'CAM'),
       ('CAMDEN', 'CAMDEN'),
       ('CAMERON', 'CAMERON'),
       ('CAMILO', 'CAMILO'),
       ('CAMPBELL', 'CAMPBELL'),
       ('CANAAN', 'CANAAN'),
       ('CANNON', 'CANNON'),
       ('CARL', 'CARL'),
       ('CARLO', 'CARLO'),
       ('CARLOS', 'CARLOS'),
       ('CARMELO', 'CARMELO'),
       ('CARSON', 'CARSON'),
       ('CARTER', 'CARTER'),
       ('CASE', 'CASE'),
       ('CASEN', 'CASEN'),
       ('CASEY', 'CASEY'),
       ('CASH', 'CASH'),
       ('CASON', 'CASON'),
       ('CASPER', 'CASPER'),
       ('CASPIAN', 'CASPIAN'),
       ('CASSIAN', 'CASSIAN'),
       ('CASSIUS', 'CASSIUS'),
       ('CASTIEL', 'CASTIEL'),
       ('CAYDEN', 'CAYDEN'),
       ('CAYSON', 'CAYSON'),
       ('CEDAR', 'CEDAR'),
       ('CEDRIC', 'CEDRIC'),
       ('CESAR', 'CESAR'),
       ('CHAD', 'CHAD'),
       ('CHANCE', 'CHANCE'),
       ('CHANDLER', 'CHANDLER'),
       ('CHANNING', 'CHANNING'),
       ('CHARBEL', 'CHARBEL'),
       ('CHARLES', 'CHARLES'),
       ('CHARLEY', 'CHARLEY'),
       ('CHARLIE', 'CHARLIE'),
       ('CHASE', 'CHASE'),
       ('CHRIS', 'CHRIS'),
       ('CHRISTIAN', 'CHRISTIAN'),
       ('CHRISTOPHER', 'CHRISTOPHER'),
       ('CIAN', 'CIAN'),
       ('CILLIAN', 'CILLIAN'),
       ('CLARENCE', 'CLARENCE'),
       ('CLARK', 'CLARK'),
       ('CLAY', 'CLAY'),
       ('CLAYTON', 'CLAYTON'),
       ('CLIFFORD', 'CLIFFORD'),
       ('CLINT', 'CLINT'),
       ('CLIVE', 'CLIVE'),
       ('CLYDE', 'CLYDE'),
       ('CODY', 'CODY'),
       ('COEN', 'COEN'),
       ('COHEN', 'COHEN'),
       ('COLBY', 'COLBY'),
       ('COLE', 'COLE'),
       ('COLEMAN', 'COLEMAN'),
       ('COLIN', 'COLIN'),
       ('COLLIN', 'COLLIN'),
       ('COLSON', 'COLSON'),
       ('COLT', 'COLT'),
       ('COLTEN', 'COLTEN'),
       ('COLTON', 'COLTON'),
       ('CONNER', 'CONNER'),
       ('CONNOR', 'CONNOR'),
       ('CONOR', 'CONOR'),
       ('CONRAD', 'CONRAD'),
       ('CONSTANTINE', 'CONSTANTINE'),
       ('COOPER', 'COOPER'),
       ('CORBIN', 'CORBIN'),
       ('COREY', 'COREY'),
       ('CORMAC', 'CORMAC'),
       ('CORTEZ', 'CORTEZ'),
       ('CORY', 'CORY'),
       ('CRAIG', 'CRAIG'),
       ('CREW', 'CREW'),
       ('CRISTIAN', 'CRISTIAN'),
       ('CRISTIANO', 'CRISTIANO'),
       ('CRISTO', 'CRISTO'),
       ('CRISTOBAL', 'CRISTOBAL'),
       ('CRISTOFER', 'CRISTOFER'),
       ('CRISTOPHER', 'CRISTOPHER'),
       ('CROSBY', 'CROSBY'),
       ('CRU', 'CRU'),
       ('CRUZ', 'CRUZ'),
       ('CULLEN', 'CULLEN'),
       ('CURREN', 'CURREN'),
       ('CURTIS', 'CURTIS'),
       ('CYRUS', 'CYRUS'),
       ('DAKOTA', 'DAKOTA'),
       ('DALE', 'DALE'),
       ('DALLAS', 'DALLAS'),
       ('DALTON', 'DALTON'),
       ('DAMARI', 'DAMARI'),
       ('DAMIAN', 'DAMIAN'),
       ('DAMIEN', 'DAMIEN'),
       ('DAMON', 'DAMON'),
       ('DAN', 'DAN'),
       ('DANE', 'DANE'),
       ('DANIEL', 'DANIEL'),
       ('DANILO', 'DANILO'),
       ('DANNY', 'DANNY'),
       ('DANTE', 'DANTE'),
       ('DARIAN', 'DARIAN'),
       ('DARIEL', 'DARIEL'),
       ('DARIEN', 'DARIEN'),
       ('DARIO', 'DARIO'),
       ('DARIUS', 'DARIUS'),
       ('DARON', 'DARON'),
       ('DARRELL', 'DARRELL'),
       ('DARREN', 'DARREN'),
       ('DARRYL', 'DARRYL');


INSERT INTO movie_actor(movie_id, actor_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 7),
       (2, 8),
       (2, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (4, 13),
       (4, 14),
       (4, 15),
       (5, 16),
       (5, 17),
       (5, 18),
       (6, 19),
       (6, 20),
       (6, 21),
       (7, 22),
       (7, 23),
       (7, 24),
       (8, 25),
       (8, 26),
       (8, 27),
       (9, 28),
       (9, 29),
       (9, 30),
       (10, 31),
       (10, 32),
       (10, 33),
       (11, 34),
       (11, 35),
       (11, 36),
       (12, 37),
       (12, 38),
       (12, 39),
       (13, 40),
       (13, 41),
       (13, 42),
       (14, 43),
       (14, 44),
       (14, 45),
       (15, 46),
       (15, 47),
       (15, 48),
       (16, 49),
       (16, 50),
       (16, 51),
       (17, 52),
       (17, 53),
       (17, 54),
       (18, 55),
       (18, 56),
       (18, 57),
       (19, 58),
       (19, 59),
       (19, 60),
       (20, 61),
       (20, 62),
       (20, 63),
       (21, 64),
       (21, 65),
       (21, 66),
       (22, 67),
       (22, 68),
       (22, 69),
       (23, 70),
       (23, 71),
       (23, 72),
       (24, 73),
       (24, 74),
       (24, 75),
       (25, 76),
       (25, 77),
       (25, 78),
       (26, 79),
       (26, 80),
       (26, 81),
       (27, 82),
       (27, 83),
       (27, 84),
       (28, 85),
       (28, 86),
       (28, 87),
       (29, 88),
       (29, 89),
       (29, 90),
       (30, 91),
       (30, 92),
       (30, 93),
       (31, 94),
       (31, 95),
       (31, 96),
       (32, 97),
       (32, 98),
       (32, 99),
       (33, 100),
       (33, 101),
       (33, 102),
       (34, 103),
       (34, 104),
       (34, 105),
       (35, 106),
       (35, 107),
       (35, 108),
       (36, 109),
       (36, 110),
       (36, 111),
       (37, 112),
       (37, 113),
       (37, 114),
       (38, 115),
       (38, 116),
       (38, 117),
       (39, 118),
       (39, 119),
       (39, 120),
       (40, 121),
       (40, 122),
       (40, 123),
       (41, 124),
       (41, 125),
       (41, 126),
       (42, 127),
       (42, 128),
       (42, 129),
       (43, 130),
       (43, 131),
       (43, 132),
       (44, 133),
       (44, 134),
       (44, 135),
       (45, 136),
       (45, 137),
       (45, 138),
       (46, 139),
       (46, 140),
       (46, 141),
       (47, 142),
       (47, 143),
       (47, 144),
       (48, 145),
       (48, 146),
       (48, 147),
       (49, 148),
       (49, 149),
       (49, 150),
       (50, 151),
       (50, 152),
       (50, 153),
       (51, 154),
       (51, 155),
       (51, 156),
       (52, 157),
       (52, 158),
       (52, 159),
       (53, 160),
       (53, 161),
       (53, 162),
       (54, 163),
       (54, 164),
       (54, 165),
       (55, 166),
       (55, 167),
       (55, 168),
       (56, 169),
       (56, 170),
       (56, 171),
       (57, 172),
       (57, 173),
       (57, 174),
       (58, 175),
       (58, 176),
       (58, 177),
       (59, 178),
       (59, 179),
       (59, 180),
       (60, 181),
       (60, 182),
       (60, 183),
       (61, 184),
       (61, 185),
       (61, 186),
       (62, 187),
       (62, 188),
       (62, 189),
       (63, 190),
       (63, 191),
       (63, 192),
       (64, 193),
       (64, 194),
       (64, 195),
       (65, 196),
       (65, 197),
       (65, 198),
       (66, 199),
       (66, 200),
       (66, 201),
       (67, 202),
       (67, 203),
       (67, 204),
       (68, 205),
       (68, 206),
       (68, 207),
       (69, 208),
       (69, 209),
       (69, 210),
       (70, 211),
       (70, 212),
       (70, 213),
       (71, 214),
       (71, 215),
       (71, 216),
       (72, 217),
       (72, 218),
       (72, 219),
       (73, 220),
       (73, 221),
       (73, 222),
       (74, 223),
       (74, 224),
       (74, 225),
       (75, 226),
       (75, 227),
       (75, 228),
       (76, 229),
       (76, 230),
       (76, 231),
       (77, 232),
       (77, 233),
       (77, 234),
       (78, 235),
       (78, 236),
       (78, 237),
       (79, 238),
       (79, 239),
       (79, 240),
       (80, 241),
       (80, 242),
       (80, 243),
       (81, 244),
       (81, 245),
       (81, 246),
       (82, 247),
       (82, 248),
       (82, 249),
       (83, 250),
       (83, 251),
       (83, 252),
       (84, 253),
       (84, 254),
       (84, 255),
       (85, 256),
       (85, 257),
       (85, 258),
       (86, 259),
       (86, 260),
       (86, 261),
       (87, 262),
       (87, 263),
       (87, 264),
       (88, 265),
       (88, 266),
       (88, 267),
       (89, 268),
       (89, 269),
       (89, 270),
       (90, 271),
       (90, 272),
       (90, 273),
       (91, 274),
       (91, 275),
       (91, 276),
       (92, 277),
       (92, 278),
       (92, 279),
       (93, 280),
       (93, 281),
       (93, 282),
       (94, 283),
       (94, 284),
       (94, 285),
       (95, 286),
       (95, 287),
       (95, 288),
       (96, 289),
       (96, 290),
       (96, 291),
       (97, 292),
       (97, 293),
       (97, 294),
       (98, 295),
       (98, 296),
       (98, 297),
       (99, 298),
       (99, 299),
       (99, 300),
       (100, 301);


insert into favorite_actor(actor_id, user_id)
values (1, 1),
       (2, 1),
       (3, 1),
       (4, 1),
       (5, 1),
       (6, 1),
       (7, 1),
       (8, 1),
       (9, 1);






